---
spring:
  profiles: dev
  jpa:
    generate-ddl: false

logging:
  file: logs/application_dev_log.txt
  level:
     ROOT: WARN     
     org.mylivedata.app: DEBUG
     org.springframework: INFO
     org.hibernate: INFO

datasource:
  initialize: false
   
flyway:
  locations: /db/migration/h2

server:
  port: 8443
  ssl:
    key-store: D:/MYWORK/keystore
    key-store-password: test123456
    key-password: test123456

thymeleaf:
  cache: false

---
spring:
   profiles: demo
   jpa:
    generate-ddl: false

logging:
   file: logs/application_log_demo.txt
   level:
     ROOT: WARN     
     org.mylivedata.app: DEBUG
     org.springframework: INFO
     org.hibernate: INFO

datasource:
  initialize: false

flyway:
  locations: /db/migration/h2
       
---
spring:
   profiles: production

logging:
   file: logs/application_log_prod.txt
   level:
     ROOT: WARN     
     org.mylivedata.app: DEBUG
     org.springframework: INFO
     org.hibernate: INFO

datasource:
  initialize: false   
  
flyway:
  locations: /db/migration/mysql  
     